### ISSUE TITLE
New output in 0.3.0 breaks VSCode `black`/`isort`

### ISSUE THREAD

**Issue by miped** [DopplerHQ/python-doppler-env#8]
## Environment

* Doppler Env version: 0.3.0
* Python version: 3.8.12
* Operating System: macOS 12.4

## Description

New doppler output breaks VSCode tools:

![image](https://user-images.githubusercontent.com/22974/176267503-dec47ab2-e61f-47a5-8388-f07fc0aa1e3d.png)

## Steps to Reproduce

I've got latest Pylance installed, and configured to use `black`/`isort` from my venv, which is created with a simple `python -m venv venv`

Settings:

```json
  "python.linting.enabled": true,
  "python.linting.pylintEnabled": true,
  "python.formatting.provider": "black",
  "python.analysis.indexing": true,
  "[python]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    },
    "editor.rulers": [88]
  },
```

## Expected Behavior

Not breaking VSCode (maybe not adding output when not running interactively? or at least providing a way to turn the output off with an env var or similar).

## Screenshots

See above.

**Comment by miped** [comment]
This is still the case as far as i can tell. Closed it by mistake.

**Comment by miped** [comment]
@ryan-blunden Will you accept a PR that makes this configurable?

**Comment by alex-chalk** [comment]
Hey, this is also causing issues for projects that use google cloud sdks, since they may run commands internally that are expecting JSON output; however, the output they get from their internal commands looks something like

```
[doppler-env]: DOPPLER_ENV environment variable set. Fetching secrets using Doppler CLI
{
  "configuration": {
    "active_configuration": "default",
    ...
  },
  "credential": {
    "access_token": "..."
  }
}
```

I'd also be very happy to contribute a fix if a maintainer can point me in the right direction! Thank you
